### ISSUE TITLE
Add UK sites

### ISSUE THREAD

**Issue by isellsoap** [isellsoap/front-end-side-of-news#10]
- [x] bbc.com
- [x] dailymail.co.uk
- [x] ft.com
- [x] independent.co.uk
- [x] mirror.co.uk
- [x] telegraph.co.uk
- [x] theguardian.com
- [x] thesun.co.uk

**Comment by isellsoap** [comment]
Added with https://github.com/isellsoap/front-end-side-of-news/commit/069681e0b4f990d552f7e6f97c0ff62476e68b88

**Comment by chrisdwheatley** [comment]
Could you add [news.sky.com](http://news.sky.com), would be good to see how we compare againts other websites. Happy to raised this as a separate Issue if required.

This is a great resource by the way!

**Comment by isellsoap** [comment]
Thanks a lot! Yes, just open a new issue.

**Comment by haroon-sheikh** [comment]
https://github.com/isellsoap/front-end-side-of-news/issues/32

**Comment by haroon-sheikh** [comment]
Added https://github.com/isellsoap/front-end-side-of-news/issues/32 for Skynews.
