### ISSUE TITLE
WebPageTest-based metrics, including Speed Index

### ISSUE THREAD

**Issue by simevidas** [isellsoap/front-end-side-of-news#21]
I haven’t yet used WebPageTest in an automated manner, but from what I understand, it can be, so you could set it up so that it runs for all sites, and and pull in all the relevant data, including Speed Index and transferred bytes.

Btw, it would be useful if the table cells contained the real values (numbers, A-F grades, etc.), I think, and that would make sorting more useful as well.

**Comment by isellsoap** [comment]
Regarding first paragraph: I have to look into this. webpagetest results aren’t always reliable (see https://mobiforge.com/design-development/measuring-page-weight). But an automation certainly makes sense. I created this issue https://github.com/isellsoap/front-end-side-of-news/issues/28 for this.

Regarding second paragraph: the real values are now shown in the cells. I also included an average calculation at the bottom of the columns.

Thanks for your input!
