### ISSUE TITLE
W3C validation column questionably useful

### ISSUE THREAD

**Issue by simevidas** [isellsoap/front-end-side-of-news#22]
Validators are certainly useful for finding potential issues with your code, but the number of errors a site gets does not tell you anything useful _per se_. This is because a site with many errors can still be completely fine, and even when the site is “valid”, that doesn’t mean much in practice. Validness just isn’t a “real” issue, like accessibility, performance, and security are.

**Comment by isellsoap** [comment]
You are 100 % right and my view on this is the same as yours. You can have a valid HTML document that has completely unsemantic markup.

But I do think, as you point out, that it _can_ be useful, especially to find potential errors in your code base. So my general attitude is that developers should at least _try_ to keep the errors to an absolute minimum. Sometimes this is also pretty easy to achieve, e.g. I found one news site that uses a doctype != HTML5 but uses HTML5 elements throughout the markup, so you could easily avoid hundreds of errors simply by using the correct doctype.

I’ll add a note in the "legend and metrics" section to point out that a valid page _per se_ isn’t an indicator of a well-crafted website.

**Comment by isellsoap** [comment]
I added a note pointing to this issue. Thanks for your input!
