### ISSUE TITLE
Font not displaying

### ISSUE THREAD

**Issue by justincavery** [isellsoap/front-end-side-of-news#29]
I'm on [Chrome/Windows](http://whatsmybrowser.org/b/80FD62E) and the fonts simply are not loading on the screen (see below).
![image](https://cloud.githubusercontent.com/assets/204469/15041879/4ee422d0-12b7-11e6-8a29-fb3033e1d28d.png)

Switching over to [IE/Windows](http://whatsmybrowser.org/b/BGI7T5W) I'm getting some letters but all capitals seem to be missing and some uses of d 
![image](https://cloud.githubusercontent.com/assets/204469/15041940/c151082e-12b7-11e6-8fa7-a1a2a4aeb9cb.png)

**Comment by isellsoap** [comment]
Thank you for the issue report. I don’t know what is causing this, super weird. On my Mac it looks good in Chrome, Safari, Opera and Firefox. I will look into it.

**Comment by isellsoap** [comment]
There seem to be a lot of issues with Fira Sans in that regard (see [here](https://github.com/google/fonts/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+%22fira+sans%22) and [here](https://github.com/vladpopa33/googlefontdirectory/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+%22fira+sans%22)). I’m now using Mozilla’s CDN for including the CSS file. Does this fix the issue?

**Comment by justincavery** [comment]
That has worked a treat, visible on both Chrome and IE on Windows now. Thanks!
