### ISSUE TITLE
Add Swiss news sites

### ISSUE THREAD

**Issue by yoyurec** [isellsoap/front-end-side-of-news#31]
- [x] http://nzz.ch
- [x] http://20min.ch
- [x] http://tagesanzeiger.ch
- [x] http://watson.ch
- [x] http://srf.ch

**Comment by isellsoap** [comment]
- [x] bernerzeitung.ch
- [x] tagblatt.ch
- [x] blick.ch

**Comment by zedpelin** [comment]
- [x] http://www.blickamabend.ch/
- [x] http://www.24heures.ch/
- [x] http://www.20min.ch/ro/

**Comment by isellsoap** [comment]
Done.

**Comment by yoyurec** [comment]
Tnx!
